services:
  db:
    image: clickhouse/clickhouse-server:22-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  migrate:
    image: amacneil/dbmate:1
    environment:
      DATABASE_URL: "clickhouse://default@db:9000/trace"
      DBMATE_NO_DUMP_SCHEMA: 1
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./db
        target: /db
        read_only: true
    command: ["--wait", "up"]
