services:
  db:
    image: clickhouse/clickhouse-server:22-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - type: bind
        source: "${HOST_DATABASE_DIR}"
        target: "/var/lib/clickhouse"
    ports:
      - "${HOST_PORT}:9000"

  insert-data:
    build: # Have to install dbmate for this container
      context: .
      dockerfile: insert-data.Dockerfile
    volumes:
      - type: bind
        source: ./insert-data.sh
        target: /app/insert-data.sh
        read_only: true
      - type: bind
        source: ./db/
        target: /app/db
        read_only: true
    working_dir: /app
    entrypoint: ./insert-data.sh
    environment:
      DATABASE_URL: "clickhouse://default@db:9000/trace"
      DBMATE_NO_DUMP_SCHEMA: 1
      CLICKHOUSE_HOST: "db"
      NUM_FILES: 12804
      NO_STATUS: "true"
    depends_on:
      - db
